version: '3'
services:
  proxy:
    build: ./proxy
    image: gerarddv/myapp-proxy:latest
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - frontend

  vote:
    build: ./vote
    image: gerarddv/myapp-vote:latest
    container_name: vote
    ports:
      - "8081:80"  # Maps container port 80 to host port 8081
    volumes:
      - ./vote:/app
    networks:
      - frontend
      - backend

  result:
    build: ./result
    image: gerarddv/myapp-result:latest
    container_name: results
    ports:
      - "8000:80"  # Maps container port 80 to host port 8000
    volumes:
      - ./result:/app
    networks:
      - frontend
      - backend

  worker:
    build: ./worker
    image: gerarddv/myapp-worker:latest
    container_name: worker
    networks:
      - backend

  redis:
    image: gerarddv/myapp-redis:latest
    container_name: redis
    expose:
      - "6379"  # Exposes container port 6379 within the backend network
    networks:
      - backend

  db:
    image: gerarddv/myapp-db:latest
    container_name: db
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"  # Exposes container port 5432 within the backend network
    networks:
      - backend

networks:
  frontend:
  backend:
