version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - frontend

  vote:
    build: ./vote
    container_name: vote
    ports:
      - "8081:80"  # Use ports to map container's port 80 to host's 8081
    volumes:
      - ./vote:/app
    networks:
      - frontend
      - backend

  result:
    build: ./result
    container_name: results
    ports:
      - "8000:80"  # Use ports to map container's port 80 to host's 8000
    volumes:
      - ./result:/app
    networks:
      - frontend
      - backend

  worker:
    build: ./worker
    container_name: worker
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - "6379"  # Expose only container port 6379 to other containers
    networks:
      - backend

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"  # Expose only container port 5432 to other containers
    networks:
      - backend

networks:
  frontend:
  backend:
