apiVersion: v1
kind: Pod
metadata:
  name: inspect-pvc
spec:
  containers:
    - name: inspect
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /app
          name: vote-claim0
  volumes:
    - name: vote-claim0
      persistentVolumeClaim:
        claimName: vote-claim0
