apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    io.kompose.service: proxy
spec:
  type: NodePort  # Expose the service externally
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30080  # Optional: explicitly specify the NodePort
  selector:
    io.kompose.service: proxy
