apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081  # Add a nodePort here
